### ISSUE TITLE
Slowing effect from Ki differences isn't really functional (In Adventurer Mode, at least).

### ISSUE THREAD

**Issue by Alceris** [Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod#19]
So, I'm playing as a Saiyan, and I've noticed that, in combat, my Ki doesn't have any effect on the speed of anyone else, but my Namekian traveling companion's does, and any enemies (at least ones that have a power level of 0 according to the new scouter) affected by him are practically frozen in time, and randomly this will include myself.

**Comment by Alceris** [comment]
I will add, I haven't actually tested it while fighting other creatures that have Ki, so it may work in those circumstances.

**Comment by Putnam3145** [comment]
Attempted fix in https://github.com/Putnam3145/SPARKING-Dwarf-Fortress-DBZ-mod/commit/ad25fb3b3ef78b6f25fba1247e70a18205683334

Cutting edge is fully playable now AFAIK. That "or op==SC_WORLD_LOADED" bit is what I tried to use to fix it, but that may not have worked. It's pretty annoying.

**Comment by Alceris** [comment]
Attempted fix didn't fix. Cutting edge also isn't playable.

**Comment by Corithian96** [comment]
This issue and #26 and definitely related. From my digging around and random printing in sparking.lua, the problem seems to be that adventurers aren't getting the thoughts of being in conflict or joining into conflict, making the function unitIsInDeadlyCombat always return false for the adventurer, while NPCs in Adventure Mode do have those two conflict thoughts. 

In addition, it seems that in 40.24 and later (and maybe somewhat earlier too?), unk_30 was actually named in dfhack as attack_velocity in one of the updates to dfhack.

I replaced all instances of unk_30 in sparking.lua with attack_velocity and changed the checks on lines 630 and 652 to check if the (unit was in deadly combat or the adventurer), and judging by how far some random boar flew with my mostly new saiyan, ki is definitely affecting attack velocity now.

I tried both the stable and cutting edge versions and this was the problem in both, I believe.

**Comment by Putnam3145** [comment]
I added that change to the structures my own damn self, too. That's embarrassing.

**Comment by Putnam3145** [comment]
14a396a ought to have fixed it.

**Comment by Putnam3145** [comment]
Closing since there hasn't been news in a while--speed changes are actually a bit of a bad idea anyway, accuracy modification is fine by itself
